name: Docker Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Images
      run: |
        for folder in RandomTextGenerator RandomTextGenerator2 RandomTextGenerator3; do
          cd "$folder"
          lowercase_folder=$(echo "$folder" | tr '[:upper:]' '[:lower:]')
          docker build -t ${{ secrets.DOCKER_USERNAME }}/$lowercase_folder:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/$lowercase_folder:latest ${{ secrets.DOCKER_USERNAME }}/$lowercase_folder:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/$lowercase_folder:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/$lowercase_folder:${{ github.sha }}
          cd ..
        done
